version: "3.8"

services:
  mini-proxy:
    build: .
    ports:
      - "7272:2022"
    environment:
      - APP_ENV=development
    networks:
      - webcore-network

networks:
  webcore-network:
    driver: bridge
