#!/usr/bin/env bash


APP_NAME="mini-proxy"
MAIN_PACKAGE="./webcore/main.go"
OUTPUT_NAME="main"
VERSION_PACKAGE="github.com/webcore-go/webcore/version"
RELEASE_PREFIX="mini-proxy"
PLATFORMS=(
    "linux/amd64"
    "linux/arm64"
    "windows/amd64"
    "darwin/amd64"
    "darwin/arm64"
)