#!/usr/bin/env bash

###############################################################################
# Project
###############################################################################

APP_NAME="mini-proxy"

###############################################################################
# Build
###############################################################################

MAIN_PACKAGE="./webcore/main.go"

OUTPUT_NAME="main"

###############################################################################
# Version Package
###############################################################################

VERSION_PACKAGE="github.com/webcore-go/webcore/version"

###############################################################################
# Release
###############################################################################

RELEASE_PREFIX="mini-proxy"

###############################################################################
# Platform
###############################################################################

PLATFORMS=(
    "linux/amd64"
    "linux/arm64"
    "windows/amd64"
    "darwin/amd64"
    "darwin/arm64"
)